#!/usr/bin/env bash

if [[ -f '/toolbox64.env' ]]; then
  # shellcheck disable=SC1091
  source "/toolbox64.env" || exit $?
else
  export TOOLBOX64_LIB=''
fi
# shellcheck source=SCRIPTDIR/../../loader/bashlib64.bash disable=SC2154
source "${TOOLBOX64_LIB}/bashlib64.bash" || exit $?

#
# Globals
#

export TOOLBOX64_DEBUG

#
# Main
#

declare cnt64_tools='sudo git tar hostname wget python3 python3-pip python3-setuptools unzip gettext bzip2 diffutils'

[[ -n "$TOOLBOX64_DEBUG" ]] && bl64_dbg_lib_enable
bl64_os_match "${BL64_OS_OL}" || {
  bl64_check_alert_unsupported
  exit $?
}
bl64_check_privilege_root &&
  bl64_pkg_setup ||
  exit $?

bl64_msg_all_enable_verbose
# shellcheck disable=SC2086
bl64_pkg_deploy $cnt64_tools ||
  exit $?

bl64_fs_cleanup_full
exit 0
