#!/usr/bin/env bash
# Template: 1.5.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

export CNT64_BASHLIB64="${CNT64_BASHLIB64:-/opt/bl64}"
# shellcheck source-path=SCRIPTDIR/../../../lib/bl64 disable=SC2015
source "${CNT64_BASHLIB64}/bashlib64-module-vcs.bash" &&
  source "${CNT64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
  source "${CNT64_BASHLIB64}/bashlib64-module-api.bash" &&
  source "${CNT64_BASHLIB64}/bashlib64-module-rnd.bash" &&
  source "${CNT64_BASHLIB64}/bashlib64-module-cryp.bash" &&
  source "${CNT64_BASHLIB64}/bashlib64-module-pkg.bash" &&
  source "${CNT64_BASHLIB64}/bashlib64-module-rbac.bash" &&
  source "${CNT64_BASHLIB64}/bashlib64-module-iam.bash" &&
  source "${CNT64_BASHLIB64}/bashlib64-module-txt.bash" &&
  source "${CNT64_BASHLIB64}/bashlib64-module-fmt.bash" &&
  source "${CNT64_BASHLIB64}/bashlib64-module-fs.bash" &&
  source "${CNT64_BASHLIB64}/bashlib64-module-bsh.bash" &&
  source "${CNT64_BASHLIB64}/bashlib64-module-xsv.bash" &&
  source "${CNT64_BASHLIB64}/bashlib64-core.bash" ||
  { echo "Error: unable to load bashlib64 (${CNT64_BASHLIB64})" && exit 1; }

#
# Globals
#

# Environment Definition. See docs/base-environment.md for details
export CNT64_DEBUG="${CNT64_DEBUG:-NONE}"
export CNT64_VERBOSE="${CNT64_VERBOSE:-FULL}"
export CNT64_USER="${CNT64_USER:-}"
export CNT64_USER_UID="${CNT64_USER_UID:-6464}"
export CNT64_USER_GID="${CNT64_USER_GID:-6464}"
export CNT64_LOCAL_ROOT="${CNT64_LOCAL_ROOT:-}"
export CNT64_LOCAL_BIN="${CNT64_LOCAL_BIN:-}"
export CNT64_INSTALLER_ROOT="${CNT64_INSTALLER_ROOT:-}"
export CNT64_OPT_ROOT="${CNT64_OPT_ROOT:-}"

#
# Functions
#

function my_create_users() {
  bl64_dbg_app_show_function
  local user_home="/home/${CNT64_USER}"
  local user_shell='/bin/bash'
  local user_geco='Container64'

  bl64_dbg_app_show_comments 'no user creation requested'
  [[ -z "$CNT64_USER" ]] && return 0

  bl64_msg_show_task "Create entrypoint user and group (${CNT64_USER}:${CNT64_USER})"
  bl64_iam_group_add \
    "$CNT64_USER" \
    "$CNT64_USER_GID" &&
    bl64_iam_user_add \
      "$CNT64_USER" \
      "$user_home" \
      "$CNT64_USER" \
      "$user_shell" \
      "$user_geco" \
      "$CNT64_USER_UID" &&
    bl64_rbac_add_root "${CNT64_USER}"
}

function my_configure_users() {
  bl64_dbg_app_show_function
  local user_mode='0750'
  local user_home="/home/${CNT64_USER}"
  local user_profile=''

  bl64_msg_show_task "Initialize user's XDG directories (${CNT64_USER})"
  bl64_bsh_xdg_create \
    "$user_home" \
    "$user_mode" \
    "$CNT64_USER" \
    "$CNT64_USER" ||
    return $?

  bl64_msg_show_task "Setup user's bash environment (${CNT64_USER})"
  user_profile="${user_home}/.bashrc"
  # shellcheck disable=SC2119
  bl64_bsh_env_store_create "$user_home" "$CNT64_USER" "$CNT64_USER" &&
    bl64_bsh_profile_rc_generate >"$user_profile" &&
    bl64_bsh_profile_path_generate >>"$user_profile" &&
    bl64_bsh_env_store_generate >>"$user_profile" &&
    bl64_fs_path_permission_set "$user_mode" "user_mode" "$CNT64_USER" "$CNT64_USER" "$BL64_VAR_OFF" "$user_profile" ||
    return $?
  user_profile="${user_home}/.bash_profile"
  bl64_bsh_profile_bash_generate >"$user_profile" &&
    bl64_fs_path_permission_set "$user_mode" "user_mode" "$CNT64_USER" "$CNT64_USER" "$BL64_VAR_OFF" "$user_profile"
}

function my_fix_repository_fedora() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'Ignore unavailable repositories (EOL)'
  bl64_txt_run_sed \
    -i 's/^skip_if_unavailable=False/skip_if_unavailable=True/g' \
    /etc/yum.repos.d/fedora*.repo
}

function my_fix_repository_centos() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'Fix EOL centos repository location to use vault'
  bl64_txt_run_sed \
    -i 's/mirrorlist/#mirrorlist/g' \
    /etc/yum.repos.d/CentOS-* &&
    bl64_txt_run_sed \
      -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' \
      /etc/yum.repos.d/CentOS-*
}

function my_fix_repository_ubuntu() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'Fix EOL ubuntu repository location to use old-release'
  bl64_txt_run_sed \
    -i -re 's/([a-z]{2}\.)?archive.ubuntu.com|security.ubuntu.com/old-releases.ubuntu.com/g' \
    /etc/apt/sources.list
}

function my_fix_repository_debian() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'Fix EOL debian repository location to use archive'
  local sources='/etc/apt/sources.list'
  printf 'deb http://archive.debian.org/debian/ stretch main contrib non-free\n' >"$sources" &&
    printf 'deb http://archive.debian.org/debian/ stretch-backports main contrib non-free\n' >>"$sources" &&
    printf 'deb http://archive.debian.org/debian-security stretch/updates main contrib non-free\n' >>"$sources"
}

function my_prepare_os() {
  bl64_dbg_app_show_function
  if bl64_os_is_distro "${BL64_OS_CNT}-8"; then
    my_fix_repository_centos
  elif bl64_os_is_distro "${BL64_OS_UB}-21.4" "${BL64_OS_UB}-22.10"; then
    my_fix_repository_ubuntu
  elif bl64_os_is_distro "${BL64_OS_DEB}-9"; then
    my_fix_repository_debian
  elif bl64_os_is_distro "${BL64_OS_FD}-36"; then
    my_fix_repository_fedora
  fi
}

function my_configure_os() {
  bl64_dbg_app_show_function
  local public_mode='0755'
  local public_owner='root'

  bl64_msg_show_task 'Create shared paths'
  bl64_fs_dir_create "$public_mode" "$public_owner" "$public_owner" \
    "$CNT64_LOCAL_ROOT" \
    "$CNT64_LOCAL_BIN" \
    "$CNT64_OPT_ROOT"
}

#######################################
# Install application packages
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package installer progress and errors
# Returns:
#   0: package installed ok
#   >0: unable to install package
#######################################
function my_install() {
  bl64_dbg_app_show_function
  local packages='sudo'

  bl64_msg_show_task 'Install required packages'
  if bl64_os_is_distro "${BL64_OS_SLES}"; then
    packages+=' findutils'
    packages+=' gawk'
  elif bl64_os_is_distro "${BL64_OS_ALP}"; then
    packages+=' curl'
  elif bl64_os_is_distro "${BL64_OS_AMZ}"; then
    packages+=' shadow-utils findutils'
  elif bl64_os_is_distro "${BL64_OS_FD}"; then
    packages+=' findutils'
    packages+=' gawk'
  elif bl64_os_is_distro "${BL64_OS_RCK}"; then
    packages+=' findutils'
  fi
  # shellcheck disable=SC2086
  bl64_pkg_deploy $packages
}

#######################################
# Initialize environment
#
# Arguments:
#   None
# Outputs:
#   Initializacion progress messages
# Returns:
#   0: initialization ok
#   >: failed to initialize
#######################################
function my_initialize() {
  bl64_dbg_app_show_function
  bl64_msg_show_about
  bl64_os_check_compatibility \
    "${BL64_OS_ARC}" \
    "${BL64_OS_ALM}" \
    "${BL64_OS_AMZ}" \
    "${BL64_OS_ALP}" \
    "${BL64_OS_CNT}" \
    "${BL64_OS_DEB}" \
    "${BL64_OS_FD}" \
    "${BL64_OS_KL}" \
    "${BL64_OS_OL}" \
    "${BL64_OS_RCK}" \
    "${BL64_OS_RHEL}" \
    "${BL64_OS_SLES}" \
    "${BL64_OS_UB}" &&
    bl64_check_export 'CNT64_INSTALLER_ROOT' &&
    bl64_check_export 'CNT64_LOCAL_ROOT' &&
    bl64_check_export 'CNT64_LOCAL_BIN' &&
    bl64_check_export 'CNT64_OPT_ROOT' &&
    bl64_cryp_setup &&
    bl64_pkg_setup &&
    bl64_check_privilege_root &&
    bl64_msg_show_setup "$BL64_VAR_DEFAULT" \
      'CNT64_INSTALLER_ROOT' \
      'CNT64_LOCAL_ROOT' \
      'CNT64_LOCAL_BIN' \
      'CNT64_OPT_ROOT'
}

#
# Main
#

bl64_lib_script_version_set '2.14.0'
bl64_msg_help_about_set 'Deploy and configure the base container environment'
bl64_dbg_set_level "$CNT64_DEBUG" && bl64_msg_set_format "$CNT64_VERBOSE" && bl64_msg_all_enable_verbose && my_initialize || exit $?
bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
my_prepare_os &&
  my_install &&
  my_configure_os &&
  my_create_users &&
  my_configure_users
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
