#!/usr/bin/env bash
# Template: 1.0.0
#######################################
# Container64 / Package installer
#
# Author: SerDigital64 (https://github.com/serdigital64)
# Repository: https://github.com/automation64/container64
# Version: 1.0.0
#
#######################################
# Copyright [2023] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# Environment Definition. See docs/base-environment.md for details
export CNT64_BASHLIB64="${CNT64_BASHLIB64:-/opt/bl64/bashlib64.bash}"
export CNT64_DEBUG="${CNT64_DEBUG:-}"

# shellcheck source=SCRIPTDIR/../../lib/bashlib64.bash
source "$CNT64_BASHLIB64" || { echo "Error: unable to load bashlib64 (${CNT64_BASHLIB64})" && exit 1; }

#
# Globals
#

# Enable development packages?
export CNT64_PYTHON_DEVELOPMENT="${CNT64_PYTHON_DEVELOPMENT:-$BL64_VAR_OFF}"

#
# Functions
#

#######################################
# Install application packages
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package installer progress and errors
# Returns:
#   0: package installed ok
#   >0: unable to install package
#######################################
function cnt64_python_install() {
  bl64_dbg_app_show_function
  local packages=''

  if bl64_os_match "${BL64_OS_UB}-22"; then
    packages='python3 python3.9 python3-pip python3-venv'
    [[ "$CNT64_PYTHON_DEVELOPMENT" == "$BL64_VAR_ON" ]] &&
      packages="${packages} python3-dev build-essential"
  fi

  bl64_msg_show_task 'deploy packages'
  # shellcheck disable=SC2086
  bl64_pkg_deploy $packages ||
    return $?

  bl64_msg_show_task 'cleanup temporary files'
  bl64_fs_cleanup_full
  return 0
}

#######################################
# Initialize environment
#
# Arguments:
#   None
# Outputs:
#   Initializacion progress messages
# Returns:
#   0: initialization ok
#   >: failed to initialize
#######################################
function cnt64_python_initialize() {
  bl64_dbg_app_show_function
  bl64_os_check_version "${BL64_OS_UB}-22" &&
    bl64_check_privilege_root &&
    bl64_pkg_setup
}

#
# Main
#

declare cnt64_python_installer_description='Install application: Python'
declare -i cnt64_python_status=0

bl64_msg_all_enable_verbose
bl64_msg_show_batch_start "$cnt64_python_installer_description"

[[ -n "$CNT64_DEBUG" ]] && bl64_dbg_lib_enable
cnt64_python_initialize &&
  cnt64_python_install
cnt64_python_status=$?

bl64_msg_show_batch_finish "$cnt64_python_status" "$cnt64_python_installer_description"
exit $cnt64_python_status
