#!/usr/bin/env bash
# Template: 1.0.0
#######################################
# Container64 / Package installer
#
# Author: SerDigital64 (https://github.com/serdigital64)
# Repository: https://github.com/automation64/container64
# Version: 1.0.0
#
#######################################
# Copyright [2023] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# Environment Definition. See docs/base-environment.md for details
export CNT64_DEBUG="${CNT64_DEBUG:-}"
export CNT64_BASHLIB64
export CNT64_OPT_ROOT
export CNT64_LOCAL_BIN

# shellcheck source=SCRIPTDIR/../../lib/bashlib64.bash
source "$CNT64_BASHLIB64" || { echo "Error: unable to load bashlib64 (${CNT64_BASHLIB64})" && exit 1; }

#
# Globals
#

export CNT64_BATSCORE_SOURCE="${CNT64_BATSCORE_SOURCE:-https://github.com/bats-core}"
export CNT64_BATSCORE_TARGET="${CNT64_BATSCORE_TARGET:-${CNT64_OPT_ROOT}/bats-core}"
export CNT64_BATSCORE_TARGET_HELPERS="${CNT64_BATSCORE_TARGET}/test_helper"

#
# Functions
#

#######################################
# Install application packages
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package installer progress and errors
# Returns:
#   0: package installed ok
#   >0: unable to install package
#######################################
function cnt64_batscore_install() {
  bl64_dbg_app_show_function
  local app_name_core="bats-core"
  local app_name_support="bats-support"
  local app_name_assert="bats-assert"
  local app_name_file="bats-file"
  local app_cli='bats'

  bl64_msg_show_task 'deploy application'
  bl64_fs_set_umask "$BL64_FS_UMASK_RW_USER_RO_ALL" &&
    bl64_vcs_git_clone "${CNT64_BATSCORE_SOURCE}/${app_name_core}.git" "${CNT64_OPT_ROOT}" 'master' &&
    bl64_fs_mkdir_full "${CNT64_BATSCORE_TARGET_HELPERS}" &&
    bl64_vcs_git_clone "${CNT64_BATSCORE_SOURCE}/${app_name_support}.git" "${CNT64_BATSCORE_TARGET_HELPERS}" 'master' &&
    bl64_vcs_git_clone "${CNT64_BATSCORE_SOURCE}/${app_name_assert}.git" "${CNT64_BATSCORE_TARGET_HELPERS}" 'master' &&
    bl64_vcs_git_clone "${CNT64_BATSCORE_SOURCE}/${app_name_file}.git" "${CNT64_BATSCORE_TARGET_HELPERS}" 'master' ||
    return $?

  bl64_msg_show_task "publish application to searchable path (${CNT64_LOCAL_BIN})"
  # shellcheck disable=SC2086
  bl64_fs_run_ln $BL64_FS_SET_LN_SYMBOLIC "${CNT64_BATSCORE_TARGET}/bin/${app_cli}" "${CNT64_LOCAL_BIN}/${app_cli}" ||
    return $?

  return 0
}

#######################################
# Initialize environment
#
# Arguments:
#   None
# Outputs:
#   Initializacion progress messages
# Returns:
#   0: initialization ok
#   >: failed to initialize
#######################################
function cnt64_batscore_initialize() {
  bl64_dbg_app_show_function

  bl64_check_export 'CNT64_LOCAL_BIN' &&
    bl64_check_export 'CNT64_OPT_ROOT' &&
    bl64_vcs_setup &&
    bl64_check_privilege_root
}

#
# Main
#

declare cnt64_batscore_installer_description='Install package: BatsCore'
declare -i cnt64_batscore_status=0

bl64_msg_all_enable_verbose
bl64_msg_show_batch_start "$cnt64_batscore_installer_description"

[[ -n "$CNT64_DEBUG" ]] && bl64_dbg_all_enable
cnt64_batscore_initialize &&
  cnt64_batscore_install
cnt64_batscore_status=$?

bl64_msg_show_batch_finish "$cnt64_batscore_status" "$cnt64_batscore_installer_description"
exit $cnt64_batscore_status
