#!/usr/bin/env bash

# shellcheck disable=SC1091
source "/toolbox.env" || exit $?
# shellcheck source=SCRIPTDIR/../../lib/bashlib64.bash disable=SC2154
source "$CNT64_BASHLIB64" || exit $?

#
# Functions
#

function cnt64_pdm_provision() {
  local packages='podman'

  bl64_msg_show_task 'deploy application'
  # shellcheck disable=SC2086
  bl64_pkg_deploy $packages

}

#
# Main
#

declare process='Install Podman CLI'
declare -i cnt64_pdm_status=0

[[ -n "$CNT64_DEBUG" ]] && bl64_dbg_lib_enable
bl64_os_check_version "${BL64_OS_OL}" &&
  bl64_check_privilege_root &&
  bl64_pkg_setup ||
  exit $?

bl64_msg_all_enable_verbose
bl64_msg_show_batch_start "$process"

cnt64_pdm_provision
cnt64_pdm_status=$?

bl64_msg_show_batch_finish "$cnt64_pdm_status" "$process"
exit $cnt64_pdm_status
