#!/usr/bin/env bash

# shellcheck disable=SC1091
source "/toolbox.env" || exit $?
# shellcheck source=SCRIPTDIR/../../lib/bashlib64.bash disable=SC2154
source "$CNT64_BASHLIB64" || exit $?

#
# Functions
#

function cnt64_mg6_provision() {
  local repository_name='mongodb-org-6.0'
  # shellcheck disable=SC2016
  local repository_url='https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/6.0/x86_64/'
  local repository_key='https://www.mongodb.org/static/pgp/server-6.0.asc'
  local packages='mongodb-org-tools mongodb-mongosh'

  bl64_msg_show_task "Enable package repository (${repository_name})"
  bl64_pkg_repository_add "$repository_name" "$repository_url" "$repository_key"

  bl64_msg_show_task 'deploy application'
  # shellcheck disable=SC2086
  bl64_pkg_deploy $packages

}

#
# Main
#

declare process='Install MongoDB Shell 6 CLI'
declare -i cnt64_mg6_status=0

[[ -n "$CNT64_DEBUG" ]] && bl64_dbg_all_enable
bl64_os_match "${BL64_OS_OL}-8" "${BL64_OS_OL}-9" || {
  bl64_check_alert_unsupported
  exit $?
}
bl64_check_privilege_root &&
  bl64_pkg_setup ||
  exit $?

bl64_msg_all_enable_verbose
bl64_msg_show_batch_start "$process"

cnt64_mg6_provision
cnt64_mg6_status=$?

bl64_msg_show_batch_finish "$cnt64_mg6_status" "$process"
exit $cnt64_mg6_status
