#!/usr/bin/env bash
# Template: 1.0.0
#######################################
# Container64 / Package installer
#
# Author: SerDigital64 (https://github.com/serdigital64)
# Repository: https://github.com/automation64/container64
# Version: 1.1.0
#
#######################################
# Copyright [2023] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# Environment Definition. See docs/base-environment.md for details
export CNT64_BASHLIB64="${CNT64_BASHLIB64:-/opt/bl64/bashlib64.bash}"
export CNT64_DEBUG="${CNT64_DEBUG:-}"

# shellcheck source=SCRIPTDIR/../../lib/bashlib64.bash
source "$CNT64_BASHLIB64" || { echo "Error: unable to load bashlib64 (${CNT64_BASHLIB64})" && exit 1; }

#
# Globals
#

export CNT64_MONGODBCLI_VERSION="${CNT64_MONGODBCLI_VERSION:-6}"

#
# Functions
#

function cnt64_mongodbcli_install_v5() {
  local repository_name=''
  local repository_platform=''
  local repository_url=''
  local repository_key=''
  local packages=''

  if bl64_os_match "${BL64_OS_OL}-8" "${BL64_OS_OL}-9"; then
    bl64_msg_show_task 'Add YUM package repository'
    repository_name='mongodb-org-5.0'
    repository_platform='x86_64'
    repository_url="https://repo.mongodb.org/yum/redhat/\$releasever/mongodb-org/5.0/${repository_platform}/"
    repository_key='https://www.mongodb.org/static/pgp/server-5.0.asc'
    packages='mongodb-atlas mongodb-atlas-cli mongodb-database-tools mongodb-mongosh'
    bl64_pkg_repository_add "$repository_name" "$repository_url" "$repository_key"
  fi
  # shellcheck disable=SC2181
  (($? != 0)) && return 1

  bl64_msg_show_task 'deploy packages'
  # shellcheck disable=SC2086
  bl64_pkg_deploy $packages
}

function cnt64_mongodbcli_install_v6() {
  local repository_name=''
  local repository_platform=''
  local repository_url=''
  local repository_key=''
  local packages=''

  if bl64_os_match "${BL64_OS_OL}-8" "${BL64_OS_OL}-9"; then
    bl64_msg_show_task 'Add YUM package repository'
    repository_name='mongodb-org-6.0'
    repository_platform='x86_64'
    repository_url="https://repo.mongodb.org/yum/redhat/\$releasever/mongodb-org/6.0/${repository_platform}/"
    repository_key='https://www.mongodb.org/static/pgp/server-6.0.asc'
    packages='mongodb-org-tools mongodb-mongosh'
    bl64_pkg_repository_add "$repository_name" "$repository_url" "$repository_key"
  fi
  # shellcheck disable=SC2181
  (($? != 0)) && return 1

  bl64_msg_show_task 'deploy packages'
  # shellcheck disable=SC2086
  bl64_pkg_deploy $packages
}

#######################################
# Install application packages
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package installer progress and errors
# Returns:
#   0: package installed ok
#   >0: unable to install package
#######################################
function cnt64_mongodbcli_install() {
  bl64_dbg_app_show_function

  case "$CNT64_MONGODBCLI_VERSION" in
  '5') cnt64_mongodbcli_install_v5 ;;
  '6') cnt64_mongodbcli_install_v6 ;;
  *) bl64_check_alert_parameter_invalid ;;
  esac
  (($? != 0)) && return 1

  bl64_msg_show_task 'cleanup temporary files'
  bl64_fs_cleanup_full
  return 0
}

#######################################
# Initialize environment
#
# Arguments:
#   None
# Outputs:
#   Initializacion progress messages
# Returns:
#   0: initialization ok
#   >: failed to initialize
#######################################
function cnt64_mongodbcli_initialize() {
  bl64_dbg_app_show_function

  bl64_check_privilege_root &&
    bl64_pkg_setup ||
    return $?

  case "$CNT64_MONGODBCLI_VERSION" in
  '5' | '6') bl64_os_check_version "${BL64_OS_OL}-8" "${BL64_OS_OL}-9" ;;
  *) bl64_check_alert_unsupported "MongoDB CLI Version: ${CNT64_MONGODBCLI_VERSION}" ;;
  esac
}

#
# Main
#

declare cnt64_mongodbcli_installer_description='Install application: MongoDB CLI'
declare -i cnt64_mongodbcli_status=0

bl64_msg_all_enable_verbose
bl64_msg_show_batch_start "$cnt64_mongodbcli_installer_description"

[[ -n "$CNT64_DEBUG" ]] && bl64_dbg_lib_enable
cnt64_mongodbcli_initialize &&
  cnt64_mongodbcli_install
cnt64_mongodbcli_status=$?

bl64_msg_show_batch_finish "$cnt64_mongodbcli_status" "$cnt64_mongodbcli_installer_description"
exit $cnt64_mongodbcli_status
