#!/usr/bin/env bash
# Template: 1.1.0
#######################################
# Installer64 / Package installer
#
# Author: SerDigital64 (https://github.com/serdigital64)
# Repository: https://github.com/automation64/installer64
# Version: 1.1.0
#
#######################################
# Copyright [2023] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# Base Installer64 parameters
export INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64/bashlib64.bash}"
export INST64_DEBUG="${INST64_DEBUG:-}"
export INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
export INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
export INST64_OPT_ROOT="${INST64_OPT_ROOT:-/opt}"

#
# Globals
#

export INST64_INSTALLER64_SOURCE="${INST64_INSTALLER64_SOURCE:-https://github.com/automation64/installer64}"
export INST64_INSTALLER64_TARGET="${INST64_INSTALLER64_TARGET:-${INST64_OPT_ROOT}/installer64}"
export INST64_INSTALLER64_VERSION="${INST64_INSTALLER64_VERSION:-latest}"

#
# Functions
#

function inst64_installer64_identify_latest() {
  local github_query='https://api.github.com/repos/automation64/installer64/releases/latest'
  case "$INST64_INSTALLER64_DOWNLOAD_TOOL" in
  'curl') curl -s "$github_query" ;;
  'wget') wget -q -O- "$github_query" ;;
  *) return 1 ;;
  esac | \
  grep '"tag_name": "v'
}

function inst64_installer64_select_version() {
  local version_target=''

  if [[ "$INST64_INSTALLER64_VERSION" == 'latest' ]]; then
    version_target="$(inst64_installer64_identify_latest)"
    version_target="${version_target##*:??}"
    version_target="${version_target%%?,*}"
  else
    version_target="$INST64_INSTALLER64_VERSION"
  fi

  [[ -n "$version_target" ]] && echo "$version_target"
}

#######################################
# Install application packages
#
# Arguments:
#   None
# Outputs:
#   Package installer progress and errors
# Returns:
#   0: package installed ok
#   >0: unable to install package
#######################################
function inst64_installer64_install() {
  local package_name='installer64-scripts.tgz'
  local package_path='releases/download'
  local package_url=''
  local package_version=''
  local app_target_owner='root'

  echo "Task: prepare destination (${INST64_INSTALLER64_TARGET})"
  if [[ ! -d "$INST64_INSTALLER64_TARGET" ]]; then
    mkdir "$INST64_INSTALLER64_TARGET" &&
      chmod 755 "$INST64_INSTALLER64_TARGET"
  fi
  cd "$INST64_INSTALLER64_TARGET" || return 1

  echo "Task: download package (${INST64_INSTALLER64_SOURCE})"
  package_version="$(inst64_installer64_select_version)" || return $?
  package_url="${INST64_INSTALLER64_SOURCE}/${package_path}/${package_version}/${package_name}"
  case "$INST64_INSTALLER64_DOWNLOAD_TOOL" in
  'curl') curl --remote-name --location "$package_url" || return $? ;;
  'wget') wget "$package_url" || return $? ;;
  *) return 1 ;;
  esac

  echo "Task: install package (${INST64_INSTALLER64_TARGET})"
  if [[ -f "$package_name" ]]; then
    tar zxf "$package_name" &&
      chown -R "${app_target_owner}:${app_target_owner}" "${INST64_INSTALLER64_TARGET}" ||
      return $?
    rm -f "$package_name"
  fi
}

#######################################
# Initialize environment
#
# Arguments:
#   None
# Outputs:
#   Initializacion progress messages
# Returns:
#   0: initialization ok
#   >: failed to initialize
#######################################
function inst64_installer64_initialize() {
  if [[ "$EUID" != '0' ]]; then
    echo 'Error: script must be run as root user'
    return 1
  fi

  if command -v 'curl' >/dev/null 2>&1; then
    INST64_INSTALLER64_DOWNLOAD_TOOL='curl'
  elif command -v 'wget' >/dev/null 2>&1; then
    INST64_INSTALLER64_DOWNLOAD_TOOL='wget'
  else
    echo 'Error: no donwload tool found (curl, wget)'
    return 1
  fi
}

#
# Main
#

declare inst64_installer64_task_title='Install application: Installer64'
declare -i inst64_installer64_status=0
declare INST64_INSTALLER64_DOWNLOAD_TOOL='none'

echo "Process: [${inst64_installer64_task_title}] started"

[[ -n "$INST64_DEBUG" ]] && set -x
inst64_installer64_initialize &&
  inst64_installer64_install
inst64_installer64_status=$?

((inst64_installer64_status == 0)) &&
  echo "Process: [${inst64_installer64_task_title}] finished successfully" ||
  echo "Process: [${inst64_installer64_task_title}] finished with errors: exit-status-${inst64_installer64_status}"
exit $inst64_installer64_status
