#!/usr/bin/env bash

# shellcheck disable=SC1091
source "/toolbox64.env" || exit $?
# shellcheck source=SCRIPTDIR/../loader/bashlib64.bash disable=SC2154
source "$TOOLBOX64_BASHLIB64" || exit $?

#
# Functions
#

tb64_gcp_provision() {
  local repository_name='google-cloud-cli'
  local repository_url='https://packages.cloud.google.com/yum/repos/cloud-sdk-el8-x86_64'
  local repository_key='https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg'
  local packages='google-cloud-cli'

  bl64_dbg_app_show_info 'repo definition: [https://cloud.google.com/sdk/docs/install#rpm]'
  bl64_msg_show_task "Enable package repository (${repository_name})"
  bl64_pkg_repository_add "$repository_name" "$repository_url" "$repository_key"

  bl64_msg_show_task 'deploy application'
  # shellcheck disable=SC2086
  bl64_pkg_deploy $packages

}

#
# Main
#

declare process='Install GCP Cloud CLI'
declare -i tb64_gcp_status=0

[[ -n "$TOOLBOX64_DEBUG" ]] && bl64_dbg_lib_enable
bl64_os_match "${BL64_OS_OL}" || {
  bl64_check_alert_unsupported
  exit $?
}
bl64_check_privilege_root &&
  bl64_pkg_setup ||
  exit $?

bl64_msg_all_enable_verbose
bl64_msg_show_batch_start "$process"

tb64_gcp_provision
tb64_gcp_status=$?

bl64_msg_show_batch_finish "$tb64_gcp_status" "$process"
exit $tb64_gcp_status
