#!/usr/bin/env bash

# shellcheck source=SCRIPTDIR/../loader/bashlib64.bash disable=SC2154
source '/bashlib64.bash' || exit $?

#
# Globals
#

export CNT64_HELPERS
export CNT64_TEST_USER

#
# Main
#

bl64_check_privilege_root &&
  bl64_check_export 'CNT64_HELPERS' &&
  bl64_check_export 'CNT64_TEST_USER' &&
  bl64_pkg_setup ||
  exit $?

bl64_msg_all_enable_verbose

# shellcheck disable=SC2086
bl64_pkg_deploy ${CNT64_HELPERS} &&
  bl64_iam_user_add "${CNT64_TEST_USER}" &&
  bl64_rbac_add_root "${CNT64_TEST_USER}" ||
  exit $?

bl64_fs_cleanup_full
exit 0
