#!/usr/bin/env bash

if [[ -f '/toolbox64.env' ]]; then
  # shellcheck disable=SC1091
  source "/toolbox64.env" || exit $?
else
  export TOOLBOX64_LIB=''
fi
# shellcheck source=SCRIPTDIR/../../loader/bashlib64.bash disable=SC2154
source "${TOOLBOX64_LIB}/bashlib64.bash" || exit $?

#
# Globals
#

export TOOLBOX64_DEBUG
export CNT64_HELPERS
export CNT64_TEST_USER

#
# Main
#

[[ -n "$TOOLBOX64_DEBUG" ]] && bl64_dbg_lib_enable
bl64_check_privilege_root &&
  bl64_check_export 'CNT64_TEST_USER' &&
  bl64_pkg_setup ||
  exit $?

bl64_msg_all_enable_verbose

if [[ -n "$CNT64_HELPERS" ]]; then
  # shellcheck disable=SC2086
  bl64_pkg_deploy ${CNT64_HELPERS} ||
    exit $?
fi

bl64_iam_user_add "${CNT64_TEST_USER}" &&
  bl64_rbac_add_root "${CNT64_TEST_USER}" ||
  exit $?

bl64_fs_cleanup_full
exit 0
