#!/usr/bin/env bash
#######################################
# Create branch from main
#
# * Template: 2.1.0
#
#######################################
# Copyright [2023] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# shellcheck source=bin/dev-set
source ./bin/dev-set || exit 1
# shellcheck source=lib/bl64/bashlib64.bash
source "${DEV_CICD_BASHLIB64}/bashlib64.bash" || exit 1

#
# Functions
#

function dev_repo_branch_create() {
  bl64_dbg_app_show_function "$@"
  local dev_repo_branch_name="$1"

  bl64_msg_show_task "switch to main branch (${DEV_CICD_BRANCH_MAIN})"
  bl64_vcs_run_git checkout "$DEV_CICD_BRANCH_MAIN" &&
    bl64_msg_show_task "create branch (${dev_repo_branch_name})" &&
    bl64_vcs_run_git checkout -b "$dev_repo_branch_name" &&
    bl64_msg_show_task "register branch in origin (${DEV_CICD_REPO_ORIGIN_NAME}/${dev_repo_branch_name})" &&
    bl64_vcs_run_git push --set-upstream "${DEV_CICD_REPO_ORIGIN_NAME}" "${dev_repo_branch_name}"
}

#
# Main
#

declare dev_repo_branch_name="${1:-feature/update}"

[[ -n "$DEV_CICD_DEBUG" ]] && bl64_dbg_all_enable

bl64_check_export 'DEV_CICD_BRANCH_MAIN' &&
  bl64_check_export 'DEV_CICD_REPO_ORIGIN_NAME' &&
  bl64_check_parameter 'dev_repo_branch_name' &&
  bl64_vcs_setup ||
  exit $?

bl64_msg_all_enable_verbose
bl64_msg_show_batch_start 'repo-branch-create'
dev_repo_branch_create "$dev_repo_branch_name"
bl64_msg_show_batch_finish $? 'repo-branch-create'
