#!/usr/bin/env bash
#######################################
# Authentication for dev-time resources
#
# * Template: 1.0.0
#
#######################################
# Copyright [2023] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# shellcheck source=bin/dev-set
source ./bin/dev-set || exit 1
# shellcheck source-path=lib/bl64
source "${DEV_CICD_BASHLIB64}/bashlib64-module-cnt.bash" &&
  source "${DEV_CICD_BASHLIB64}/bashlib64-core.bash" || exit 1

#
# Functions
#

function dev_auth_cosign_ghtoken() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'Cosign login with GitHub token'
  bl64_dbg_app_trace_start
  "$DEV_LIB_GH_BIN" \
    auth token |
    "$DEV_LIB_COSIGN_BIN" \
      login \
      "$DEV_AUTH_COSIGN_SERVER" \
      --password-stdin \
      --username="$DEV_AUTH_COSIGN_USER"
  bl64_dbg_app_trace_stop
}

function dev_auth_cosign_password() {
  bl64_dbg_app_show_function
  bl64_msg_show_task 'Cosign login with user+password'
  bl64_dbg_app_trace_start
  "$DEV_LIB_COSIGN_BIN" \
    login \
    "$DEV_AUTH_COSIGN_SERVER" \
    --username="$DEV_AUTH_COSIGN_USER" \
    --password="$DEV_AUTH_COSIGN_PASSWORD"
  bl64_dbg_app_trace_stop
}

function dev_auth_cosign() {
  bl64_dbg_app_show_function
  case "$DEV_AUTH_COSIGN_TYPE" in
  'GITHUB') dev_auth_cosign_ghtoken ;;
  *) dev_auth_cosign_password ;;
  esac
}

#
# Main
#

[[ -n "$DEV_CICD_DEBUG" ]] && bl64_dbg_all_enable

bl64_check_export 'DEV_AUTH_COSIGN_USER' &&
  bl64_check_export 'DEV_AUTH_COSIGN_SERVER' &&
  bl64_check_export 'DEV_AUTH_COSIGN_TYPE' &&
  bl64_check_export 'DEV_LIB_COSIGN_BIN' &&
  bl64_check_command_search_path "$DEV_LIB_COSIGN_BIN" ||
  exit $?

if [[ "$DEV_AUTH_COSIGN_TYPE" == 'GITHUB' ]]; then
  bl64_check_export 'DEV_LIB_GH_BIN' &&
    bl64_check_command_search_path "$DEV_LIB_GH_BIN" ||
    exit $?
else
  bl64_check_export 'DEV_AUTH_COSIGN_PASSWORD' ||
    exit $?
fi

bl64_msg_all_enable_verbose
bl64_msg_show_batch_start 'auth-cosign'
dev_auth_cosign
bl64_msg_show_batch_finish $? 'auth-cosign'
