#!/usr/bin/env bash
#######################################
# Authentication for dev-time resources
#
# * Template: 1.0.0
#
#######################################
# Copyright [2023] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# shellcheck source=bin/dev-set
source ./bin/dev-set || exit 1
# shellcheck source-path=lib/bl64
source "${DEV_CICD_BASHLIB64}/bashlib64-core.bash" || exit 1

#
# Functions
#

function dev_auth_github() {
  bl64_dbg_app_show_function
  "$DEV_LIB_GH_BIN" \
    auth login \
    --scopes "$DEV_AUTH_GH_SCOPES"
}

#
# Main
#

[[ -n "$DEV_CICD_DEBUG" ]] && bl64_dbg_all_enable
bl64_check_export 'DEV_LIB_GH_BIN' &&
  bl64_check_command_search_path "$DEV_LIB_GH_BIN" ||
  exit $?

bl64_msg_all_enable_verbose
bl64_msg_show_batch_start 'auth-github'
dev_auth_github
bl64_msg_show_batch_finish $? 'auth-github'
