#!/usr/bin/env bash
#######################################
# Lint shell source code
#
# * Check is done using shellcheck
# * TestManSH is used to manage linting environment
# * Template: 6.0.0
#
#######################################
# Copyright [2023] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# shellcheck source=bin/dev-set
source ./bin/dev-set || exit 1
# shellcheck source-path=lib/bl64
source "${DEV_CICD_BASHLIB64}/bashlib64-module-txt.bash" &&
  source "${DEV_CICD_BASHLIB64}/bashlib64-module-fmt.bash" &&
  source "${DEV_CICD_BASHLIB64}/bashlib64-module-fs.bash" &&
  source "${DEV_CICD_BASHLIB64}/bashlib64-core.bash" ||
  exit 1

#
# Functions
#

function dev_lint_bash() {
  bl64_dbg_app_show_function "$@"
  local target="$*"
  local current=''

  if [[ -z "$target" ]]; then
    target="$(bl64_fs_find_files "$DEV_CICD_LINT_BASH_SOURCE")" ||
      return $?
  fi
  for current in $target; do
    bl64_msg_show_phase "lint target: ${current}"
    "$DEV_LIB_TESTMANSH_BIN" -t -a -V NONE -c "$current" ||
      return $?
  done
}

#
# Main
#

declare dev_lint_target="${*:-}"

[[ -n "$DEV_CICD_DEBUG" ]] && bl64_dbg_all_enable

bl64_check_export 'DEV_CICD_LINT_BASH_CFG' &&
  bl64_check_export 'DEV_LIB_TESTMANSH_BIN' &&
  bl64_check_command_search_path "$DEV_LIB_TESTMANSH_BIN" ||
  exit $?

bl64_msg_all_enable_verbose
bl64_msg_show_batch_start 'lint-bash'
dev_lint_bash "$dev_lint_target"
bl64_msg_show_batch_finish $? 'lint-bash'
