#!/usr/bin/env bash
#######################################
# Open sandbox environment
#
# * Template: 1.4.0
#
#######################################
# Copyright [2023] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# shellcheck source=bin/dev-set
source ./bin/dev-set || exit 1
# shellcheck source=lib/bl64/bashlib64.bash
source "${DEV_CICD_BASHLIB64}/bashlib64.bash" || exit 1

#
# Functions
#

function dev_lab_open() {
  bl64_dbg_app_show_function "$@"
  local dev_lab_image="$1"
  local dev_lab_path_source='/source'
  local dev_lab_path_project='/project'
  local dev_lab_entrypoint='bash'

  bl64_msg_show_task "open sanbox environment (${dev_lab_image})"
  bl64_cnt_run_interactive \
    --entrypoint="$dev_lab_entrypoint" \
    --workdir="$dev_lab_path_project" \
    --mount "type=bind,source=${DEV_SRC},target=${dev_lab_path_source},readonly" \
    --mount "type=bind,source=${DEV_ROOT},target=${dev_lab_path_project},readonly" \
    "${DEV_CICD_LAB_REGISTRY}/${dev_lab_image}"
}

#
# Main
#

declare dev_lab_image="${1:-$DEV_CICD_LAB_IMAGE}"

[[ -n "$DEV_CICD_DEBUG" ]] && bl64_dbg_all_enable
bl64_check_parameter 'dev_lab_image' &&
  bl64_check_export 'DEV_CICD_LAB_REGISTRY' &&
  bl64_cnt_setup ||
  exit $?

bl64_msg_all_enable_verbose
bl64_msg_show_batch_start 'lab'
dev_lab_open "$dev_lab_image"
bl64_msg_show_batch_finish $? 'lab'
