#!/usr/bin/env bash

# shellcheck disable=SC1091
source "/toolbox.env" || exit $?
# shellcheck source=SCRIPTDIR/../../loader/bashlib64.bash disable=SC2154
source "${CNT64_LIB}/bashlib64.bash" || exit $?

#
# Globals
#

export CNT64_DEBUG
export CNT64_ANSIBLE_USER
export CNT64_ANSIBLE_HOME

#
# Main
#

[[ -n "$CNT64_DEBUG" ]] && bl64_dbg_all_enable
bl64_check_privilege_root &&
  bl64_check_export 'CNT64_ANSIBLE_USER' &&
  bl64_check_export 'CNT64_ANSIBLE_HOME' ||
  exit $?

bl64_msg_all_enable_verbose

bl64_msg_show_task "Create ansible installation owner user (${CNT64_ANSIBLE_USER})" &&
  bl64_iam_user_add "$CNT64_ANSIBLE_USER" "$CNT64_ANSIBLE_HOME" &&
  bl64_fs_fix_permissions 'go+r' 'go+rx' "$CNT64_ANSIBLE_HOME" ||
  exit $?

exit 0
