#!/usr/bin/env bash
# Template: 1.2.0
#######################################
# Container64 / Setup container image
#
# Author: SerDigital64 (https://github.com/serdigital64)
# Repository: https://github.com/automation64/container64
# Version: 1.0.0
#
#######################################
# Copyright [2023] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# Environment Definition. See docs/base-environment.md for details
export CNT64_BASHLIB64="${CNT64_BASHLIB64:-/opt/bl64/bashlib64.bash}"
export CNT64_DEBUG="${CNT64_DEBUG:-}"
export CNT64_USER

# shellcheck source=SCRIPTDIR/../../lib/bashlib64.bash
source "$CNT64_BASHLIB64" || { echo "Error: unable to load bashlib64 (${CNT64_BASHLIB64})" && exit 1; }

#
# Globals
#

#
# Functions
#

function cnt64_setup_configure_user() {
  bl64_dbg_app_show_function
  local user_home="/home/${CNT64_USER}"
  local bashrc_d="${user_home}/.bashrc.d"

  bl64_msg_show_task "Update user's search path definition (${bashrc_d})"
  printf 'PATH="${PATH}:%s"\n' "${user_home}/.krew/bin" |
    bl64_rbac_run_command "$CNT64_USER" tee "${bashrc_d}/krew.env"
}

#######################################
# Initialize environment
#
# Arguments:
#   None
# Outputs:
#   Initializacion progress messages
# Returns:
#   0: initialization ok
#   >: failed to initialize
#######################################
function cnt64_setup_initialize() {
  bl64_dbg_app_show_function
  bl64_check_export 'CNT64_USER' &&
    bl64_os_check_version \
      "${BL64_OS_OL}-9" &&
    bl64_check_privilege_root
}

#
# Main
#

declare cnt64_setup_installer_description='Setup Container64 image'

bl64_msg_all_enable_verbose
bl64_msg_show_batch_start "$cnt64_setup_installer_description"

[[ -n "$CNT64_DEBUG" ]] && bl64_dbg_lib_enable
cnt64_setup_initialize &&
  cnt64_setup_configure_user

bl64_msg_show_batch_finish $? "$cnt64_setup_installer_description"
