#!/usr/bin/env bash
# Template: 1.5.0
#######################################
# Container64 / Setup container image
#
# Author: SerDigital64 (https://github.com/serdigital64)
# Repository: https://github.com/automation64/container64
# Version: 2.0.0
#
#######################################
# Copyright [2023] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# Environment Definition. See docs/base-environment.md for details
export CNT64_BASHLIB64="${CNT64_BASHLIB64:-/opt/bl64}"
export CNT64_DEBUG="${CNT64_DEBUG:-}"
export CNT64_USER

# shellcheck source-path=lib/bl64 disable=SC2015
source "${CNT64_BASHLIB64}/bashlib64-module-rnd.bash" &&
  source "${CNT64_BASHLIB64}/bashlib64-module-cryp.bash" &&
  source "${CNT64_BASHLIB64}/bashlib64-module-pkg.bash" &&
  source "${CNT64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
  source "${CNT64_BASHLIB64}/bashlib64-module-vcs.bash" &&
  source "${CNT64_BASHLIB64}/bashlib64-module-api.bash" &&
  source "${CNT64_BASHLIB64}/bashlib64-module-rbac.bash" &&
  source "${CNT64_BASHLIB64}/bashlib64-module-iam.bash" &&
  source "${CNT64_BASHLIB64}/bashlib64-module-txt.bash" &&
  source "${CNT64_BASHLIB64}/bashlib64-module-fmt.bash" &&
  source "${CNT64_BASHLIB64}/bashlib64-module-fs.bash" &&
  source "${CNT64_BASHLIB64}/bashlib64-core.bash" || { echo "Error: unable to load bashlib64 (${CNT64_BASHLIB64})" && exit 1; }

#
# Globals
#

#
# Functions
#

function cnt64_setup_prepare_os() {
  bl64_dbg_app_show_function
  if bl64_os_is_distro "${BL64_OS_OL}-8"; then
    bl64_msg_show_task 'Enable EPEL repository'
    bl64_pkg_deploy 'oracle-epel-release-el8'
  elif bl64_os_is_distro "${BL64_OS_OL}-9"; then
    bl64_msg_show_task 'Enable EPEL repository'
    bl64_pkg_deploy 'oracle-epel-release-el9'
  fi
}

function cnt64_setup_select_packages() {
  bl64_dbg_app_show_function
  local packages=''

  # Distro specific
  if bl64_os_is_distro "${BL64_OS_OL}"; then
    # Python3
    packages+=" python3 python3-pip python3-setuptools"
    # File management tools
    packages+=" tar unzip bzip2 xz mc file lsof"
    # Networking tools
    packages+=" hostname tcpdump bind-utils net-tools telnet nmap iptraf-ng"
    # File transfer tools
    packages+=" ftp wget rsync restic rclone"
    # Performance tools
    packages+=" sysstat strace ltrace btop htop stress-ng"
    # Code management tools
    packages+=" git diffutils patch"
    # Shells
    packages+=" zsh csh bash-completion screen tmux fish"
    # Text utils
    packages+=" ripgrep nano less jq gettext gawk tldr most"
    # Certificate tools
    packages+=" dirmngr gnupg2 openssl"
  fi
  if bl64_os_is_distro "${BL64_OS_OL}-9"; then
    # Text utils
    packages+=" bat"
    # Python3
    packages+=" pipx"
  fi

  [[ -n "$packages" ]] && echo "$packages"
}

function cnt64_setup_create_users() {
  bl64_dbg_app_show_function
  local user_home="/home/${CNT64_USER}"
  local user_shell='/bin/bash'

  bl64_msg_show_task "Create entrypoint user (${CNT64_USER})"
  bl64_iam_user_add \
    "$CNT64_USER" \
    "$user_home" \
    "$BL64_VAR_DEFAULT" \
    "$user_shell" &&
    bl64_rbac_add_root "${CNT64_USER}"
}

function cnt64_setup_configure_users() {
  bl64_dbg_app_show_function
  local user_mode='0750'
  local user_home="/home/${CNT64_USER}"
  local user_profile=''
  local user_bashrc_d="${user_home}/.bashrc.d"

  bl64_msg_show_task "Initialize user's XDG directories (${CNT64_USER})"
  bl64_iam_xdg_create "$user_home" ||

  bl64_msg_show_task "Create modular bashr store (${user_bashrc_d})"
  bl64_fs_create_dir "$user_mode" "$CNT64_USER" "$CNT64_USER" \
    "$user_bashrc_d"

  bl64_msg_show_task "Setup user's bash environment (${CNT64_USER})"
  if bl64_os_is_distro "${BL64_OS_ALP}"; then
    user_profile="${user_home}/.bash_profile"
    # shellcheck disable=SC2016
    printf \
      '#!/usr/bin/env bash
# added-by-installer64 #
declare module=""
export PATH="$HOME/.local/bin:$HOME/bin:$PATH"
if [[ -d "${HOME}/.bashrc.d" ]]; then
  for module in ${HOME}/.bashrc.d/*; do
    [[ -r "$module" ]] && source "$module"
  done
fi\n' >"$user_profile" &&
      bl64_fs_set_permissions "$user_mode" "$CNT64_USER" "$CNT64_USER" "$user_profile"
  elif bl64_os_is_distro "${BL64_OS_UB}"; then
    user_profile="${user_home}/.bashrc"
    # shellcheck disable=SC2016
    printf \
      '\n# added-by-installer64 #
declare module=""
if [[ -d "${HOME}/.bashrc.d" ]]; then
  for module in ${HOME}/.bashrc.d/*; do
    [[ -r "$module" ]] && source "$module"
  done
fi\n' >>"$user_profile"
  fi
}

function cnt64_setup_install_packages() {
  bl64_dbg_app_show_function
  local packages=''
  bl64_msg_show_task 'deploy packages'
  packages="$(cnt64_setup_select_packages)" ||
    return $?
  # shellcheck disable=SC2086
  bl64_pkg_deploy $packages
}

#######################################
# Initialize environment
#
# Arguments:
#   None
# Outputs:
#   Initializacion progress messages
# Returns:
#   0: initialization ok
#   >: failed to initialize
#######################################
function cnt64_setup_initialize() {
  bl64_dbg_app_show_function

  bl64_os_check_version \
    "${BL64_OS_OL}-8" \
    "${BL64_OS_OL}-9" &&
    bl64_check_export 'CNT64_USER' &&
    bl64_check_privilege_root &&
    bl64_cryp_setup &&
    bl64_pkg_setup
}

#
# Main
#

declare cnt64_setup_installer_description='Setup Container64 image'

bl64_msg_all_enable_verbose
bl64_msg_show_batch_start "$cnt64_setup_installer_description"

[[ -n "$CNT64_DEBUG" ]] && bl64_dbg_all_enable
cnt64_setup_initialize &&
  cnt64_setup_prepare_os &&
  cnt64_setup_install_packages &&
  cnt64_setup_create_users &&
  cnt64_setup_configure_users
bl64_msg_show_batch_finish $? "$cnt64_setup_installer_description"
