#!/usr/bin/env bash
# Template: 1.1.0
#######################################
# Copyright SerDigital64 - https://github.com/serdigital64
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

export CNT64_BL64_PATH="${CNT64_BL64_PATH:-/opt/bl64}"
source "${CNT64_BL64_PATH}/bashlib64-module-rnd.bash" &&
  source "${CNT64_BL64_PATH}/bashlib64-module-xsv.bash" &&
  source "${CNT64_BL64_PATH}/bashlib64-module-bsh.bash" &&
  source "${CNT64_BL64_PATH}/bashlib64-module-cryp.bash" &&
  source "${CNT64_BL64_PATH}/bashlib64-module-pkg.bash" &&
  source "${CNT64_BL64_PATH}/bashlib64-module-rxtx.bash" &&
  source "${CNT64_BL64_PATH}/bashlib64-module-vcs.bash" &&
  source "${CNT64_BL64_PATH}/bashlib64-module-api.bash" &&
  source "${CNT64_BL64_PATH}/bashlib64-module-rbac.bash" &&
  source "${CNT64_BL64_PATH}/bashlib64-module-iam.bash" &&
  source "${CNT64_BL64_PATH}/bashlib64-module-txt.bash" &&
  source "${CNT64_BL64_PATH}/bashlib64-module-fmt.bash" &&
  source "${CNT64_BL64_PATH}/bashlib64-module-fs.bash" &&
  source "${CNT64_BL64_PATH}/bashlib64-core.bash" || exit $?

export CNT64_BL64_VERSION='23.5.1'

# Environment Definition. See docs/base-environment.md for details
export CNT64_DEBUG="${CNT64_DEBUG:-NONE}"
export CNT64_VERBOSE="${CNT64_VERBOSE:-FULL}"
export CNT64_USER="${CNT64_USER:-}"

function my_configure_os() {
  bl64_dbg_app_show_function
  if bl64_os_is_distro "${BL64_OS_UB}"; then
    # Base image doesn't have locales, need to generate at least for en
    bl64_msg_show_task 'Generate en_US.UTF-8 locale'
    localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
  fi
}

function my_select_packages() {
  bl64_dbg_app_show_function
  local packages=''
  if bl64_os_is_distro "${BL64_OS_UB}-22"; then
    # OS dependant tools
    packages+=" apt-utils apt-transport-https lsb-release tzdata xdg-user-dirs locales"
    # File management tools
    packages+=" tar file lsof"
    # Networking tools
    packages+=" dnsutils net-tools"
    # File transfer tools
    packages+=" ftp wget"
    # Performance tools
    packages+=" hostname procps psmisc htop"
    # Shells
    packages+=" bash-completion direnv"
    # Code management tools
    packages+=" diffutils patch make"
    # Text utils
    packages+=" nano less jq gettext gawk readline-common tldr most"
    # Certificate tools
    packages+=" dirmngr gnupg2 ca-certificates openssl"
  elif bl64_os_is_distro "${BL64_OS_UB}-24"; then
    # OS dependant tools
    packages+=" apt-utils apt-transport-https lsb-release tzdata xdg-user-dirs locales"
    # File management tools
    packages+=" tar file lsof"
    # Networking tools
    packages+=" dnsutils net-tools"
    # File transfer tools
    packages+=" ftp wget"
    # Performance tools
    packages+=" hostname procps psmisc htop"
    # Shells
    packages+=" bash-completion direnv"
    # Code management tools
    packages+=" diffutils patch make"
    # Text utils
    packages+=" nano less jq gettext gawk readline-common tldr most"
    # Certificate tools
    packages+=" dirmngr gnupg2 ca-certificates openssl"
  fi
  [[ -n "$packages" ]] && echo "$packages"
}

function my_install_packages() {
  bl64_dbg_app_show_function
  local packages=''
  bl64_msg_show_task 'deploy packages'
  packages="$(my_select_packages)" ||
    return $?
  # shellcheck disable=SC2086
  bl64_pkg_install $packages
}

function my_install() {
  bl64_dbg_app_show_function

  my_install_packages &&
    my_configure_os
}

function my_initialize() {
  bl64_dbg_app_show_function

  bl64_dbg_set_level "$CNT64_DEBUG" &&
    bl64_msg_set_format "$CNT64_VERBOSE" ||
    return $?

  bl64_msg_help_show_about

  bl64_lib_script_minver_check "$CNT64_BL64_VERSION" &&
    bl64_os_check_version \
      "${BL64_OS_UB}-22" \
      "${BL64_OS_UB}-24" &&
    bl64_check_export 'CNT64_USER' &&
    bl64_check_privilege_root &&
    bl64_cryp_setup &&
    bl64_pkg_setup
}

bl64_lib_script_version_set '5.0.0'
bl64_msg_help_set_about 'Setup container image'
my_initialize || exit $?

bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
my_install
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
