#!/usr/bin/env bash

# shellcheck source=SCRIPTDIR/../loader/bashlib64.bash disable=SC2154
source "${TOOLBOX64_LIB}/bashlib64.bash" || exit $?

#
# Main
#

bl64_msg_all_enable_verbose

# shellcheck disable=SC2086
bl64_pkg_deploy \
  ${CNT64_SYSTEMD_PREREQS} \
  ${CNT64_SYSTEMD_PACKAGES} \
  ${CNT64_SUDO_PREREQS} \
  ${CNT64_SUDO_PACKAGES} \
  ${CNT64_PYTHON3_PREREQS} \
  ${CNT64_PYTHON3_PACKAGES} ||
  exit $?

bl64_iam_user_add "${CNT64_TEST_USER}" &&
  bl64_rbac_add_root "${CNT64_TEST_USER}" ||
  exit $?

bl64_fs_run_chmod '0755' "$CNT64_HELPER_ANSIBLE" &&
  bl64_rbac_run_command "${CNT64_TEST_USER}" "$CNT64_HELPER_ANSIBLE" ||
  exit $?

bl64_msg_show_task 'Configure systemctl multi-user'
systemctl set-default multi-user.target

bl64_fs_cleanup_full
bl64_fs_rm_file "$CNT64_HELPER_ANSIBLE"
exit 0
