#!/usr/bin/env bash
source '/bashlib64.bash' || exit 1

bl64_msg_all_enable_verbose

bl64_msg_show_task "create test user (${CNT64_TEST_USER})"
bl64_iam_user_add "${CNT64_TEST_USER}" ||
  exit $?

bl64_msg_show_task "install os packages"
bl64_pkg_deploy "${CNT64_HELPERS}" ||
  exit $?

bl64_msg_show_task "install TFSec (${CNT64_SRC_TFSEC})"
bl64_rxtx_web_get_file "${CNT64_SRC_TFSEC}" "${CNT64_BIN_TFSEC}" '0' '0755' ||
  exit $?

bl64_msg_show_task "install Terraform (${CNT64_SRC_TERRAFORM})"
bl64_rxtx_web_get_file "${CNT64_SRC_TERRAFORM}" "${CNT64_BIN_TERRAFORM}.zip" &&
  bl64_arc_open_zip "${CNT64_BIN_TERRAFORM}.zip" "${CNT64_LOCAL_BIN}" ||
  exit $?

bl64_msg_show_task "install TFLint (${CNT64_SRC_TFLINT})"
bl64_rxtx_web_get_file "${CNT64_SRC_TFLINT}" "${CNT64_BIN_TFLINT}.zip" &&
  bl64_arc_open_zip "${CNT64_BIN_TFLINT}.zip" "${CNT64_LOCAL_BIN}" ||
  exit $?

bl64_fs_cleanup_full
exit 0
