#!/usr/bin/env bash
# Template: 1.1.0
#######################################
# Container64 / Setup container image
#
# Author: SerDigital64 (https://github.com/serdigital64)
# Repository: https://github.com/automation64/container64
# Version: 1.5.0
#
#######################################
# Copyright [2023] [serdigital64@gmail.com]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################

#
# Imports
#

# Environment Definition. See docs/base-environment.md for details
export CNT64_BASHLIB64="${CNT64_BASHLIB64:-/opt/bl64}"
export CNT64_DEBUG="${CNT64_DEBUG:-}"
export CNT64_USER

# shellcheck source=lib/bl64/bashlib64.bash
source "${CNT64_BASHLIB64}/bashlib64.bash" || { echo "Error: unable to load bashlib64 (${CNT64_BASHLIB64})" && exit 1; }

#
# Globals
#

#
# Functions
#

function cnt64_setup_select_packages() {
  bl64_dbg_app_show_function
  local packages=''
  if bl64_os_match "${BL64_OS_ALP}"; then
    packages='git mawk curl python3 py3-pip musl musl-utils musl-locales tzdata gettext jq'
  elif bl64_os_match "${BL64_OS_ALM}"; then
    packages='git diffutils python3 python3-pip python3-setuptools unzip wget gettext jq'
  elif bl64_os_match "${BL64_OS_CNT}"; then
    packages='git diffutils hostname wget python3 python3-pip python3-setuptools unzip gettext jq'
  elif bl64_os_match "${BL64_OS_DEB}"; then
    packages='git wget curl gawk python3 python3-pip python3-venv unzip gettext jq'
  elif bl64_os_match "${BL64_OS_FD}"; then
    packages='git diffutils hostname wget python3-pip findutils unzip gettext jq'
  elif bl64_os_match "${BL64_OS_OL}"; then
    packages='git tar hostname wget python3 python3-pip python3-setuptools unzip gettext jq'
  elif bl64_os_match "${BL64_OS_RHEL}"; then
    packages='git hostname diffutils wget python3 python3-pip python3-setuptools unzip gettext jq'
  elif bl64_os_match "${BL64_OS_RCK}"; then
    packages='git hostname diffutils wget python3 python3-pip python3-setuptools findutils unzip gettext jq'
  elif bl64_os_match "${BL64_OS_SLES}"; then
    packages='git hostname wget gawk gettext-runtime python3 python3-pip unzip tar jq'
  elif bl64_os_match "${BL64_OS_UB}"; then
    packages='git wget curl gawk python3 python3-pip python3-venv unzip gettext jq'
  fi
  [[ -n "$packages" ]] && echo "$packages"
}

function cnt64_setup_create_users() {
  bl64_dbg_app_show_function
  local user_mode='0755'
  local user_shell='/bin/bash'
  local user_home="/home/${CNT64_USER}"
  local xdg_config="${user_home}/.config"
  local xdg_cache="${user_home}/.cache"
  local xdg_local="${user_home}/.local"
  local user_profile="${user_home}/.bash_profile"

  bl64_msg_show_task "Create entrypoint user (${CNT64_USER})"
  bl64_iam_user_add \
    "$CNT64_USER" \
    "$BL64_VAR_DEFAULT" \
    "$BL64_VAR_DEFAULT" \
    "$user_shell" &&
    bl64_rbac_add_root "${CNT64_USER}" ||
    return $?

  bl64_msg_show_task "Initialize user's XDG directories (${CNT64_USER})"
  bl64_fs_create_dir "$user_mode" "$CNT64_USER" "$CNT64_USER" \
    "$xdg_config" \
    "$xdg_local" \
    "$xdg_cache" \
    "${xdg_local}/bin" \
    "${xdg_local}/lib" \
    "${xdg_local}/share" \
    "${xdg_local}/state" ||
    return $?

  if bl64_os_match "${BL64_OS_ALP}"; then
    bl64_msg_show_task "Setup user's bash environment (${CNT64_USER})"
    # shellcheck disable=SC2016
    printf 'PATH="$HOME/.local/bin:$HOME/bin:$PATH"\n' >"$user_profile" &&
      bl64_fs_set_permissions "$user_mode" "$CNT64_USER" "$CNT64_USER" "$user_profile" ||
      return $?
  fi
  return 0
}

function cnt64_setup_install_packages() {
  bl64_dbg_app_show_function
  local packages=''

  bl64_msg_show_task 'deploy packages'
  packages="$(cnt64_setup_select_packages)" ||
    return $?
  # shellcheck disable=SC2086
  bl64_pkg_deploy $packages
}

#######################################
# Install application packages
#
# Arguments:
#   None. Parameters are imported from Globals
# Outputs:
#   Package installer progress and errors
# Returns:
#   0: package installed ok
#   >0: unable to install package
#######################################
function cnt64_setup_install() {
  bl64_dbg_app_show_function

  cnt64_setup_install_packages &&
    cnt64_setup_create_users ||
    return $?

  bl64_msg_show_task 'cleanup temporary files'
  bl64_fs_cleanup_full
  return 0
}

#######################################
# Initialize environment
#
# Arguments:
#   None
# Outputs:
#   Initializacion progress messages
# Returns:
#   0: initialization ok
#   >: failed to initialize
#######################################
function cnt64_setup_initialize() {
  bl64_dbg_app_show_function

  bl64_os_check_version \
    "${BL64_OS_ALM}" \
    "${BL64_OS_ALP}" \
    "${BL64_OS_CNT}" \
    "${BL64_OS_DEB}" \
    "${BL64_OS_FD}" \
    "${BL64_OS_OL}" \
    "${BL64_OS_RCK}" \
    "${BL64_OS_RHEL}" \
    "${BL64_OS_SLES}" \
    "${BL64_OS_UB}" &&
    bl64_check_export 'CNT64_USER' &&
    bl64_check_privilege_root &&
    bl64_pkg_setup
}

#
# Main
#

declare cnt64_setup_installer_description='Setup Container64 image'

bl64_msg_all_enable_verbose
bl64_msg_show_batch_start "$cnt64_setup_installer_description"

[[ -n "$CNT64_DEBUG" ]] && bl64_dbg_all_enable
cnt64_setup_initialize &&
  cnt64_setup_install

bl64_msg_show_batch_finish $? "$cnt64_setup_installer_description"
