#!/usr/bin/env bash

# shellcheck disable=SC1091
source "/toolbox64.env" || exit $?
# shellcheck source=SCRIPTDIR/../../loader/bashlib64.bash disable=SC2154
source "${TOOLBOX64_LIB}/bashlib64.bash" || exit $?

#
# Globals
#

export CNT64_TEST_USER

#
# Main
#

bl64_os_match "$BL64_OS_OL" &&
  bl64_check_privilege_root &&
  bl64_check_export 'CNT64_TEST_USER' ||
  exit $?

bl64_msg_all_enable_verbose
bl64_msg_show_task "create test user (${CNT64_TEST_USER})" &&
  bl64_iam_user_add "${CNT64_TEST_USER}" ||
  exit $?

exit 0
