#!/usr/bin/env bash

# shellcheck source=SCRIPTDIR/../loader/bashlib64.bash
source '/bashlib64.bash' || exit $?

#
# Globals
#

export CNT64_LINT_USER

#
# Main
#

bl64_os_match "$BL64_OS_ALP" &&
  bl64_check_privilege_root &&
  bl64_check_export 'CNT64_LINT_USER' ||
  exit $?

bl64_msg_all_enable_verbose
bl64_msg_show_task "create lint user (${CNT64_LINT_USER})" &&
  bl64_iam_user_add "$CNT64_LINT_USER" ||
  exit $?

bl64_fs_cleanup_full
exit 0
