#!/usr/bin/env bash

# shellcheck disable=SC1091
source "/toolbox64.env" || exit $?
# shellcheck source=SCRIPTDIR/../../loader/bashlib64.bash disable=SC2154
source "${TOOLBOX64_LIB}/bashlib64.bash" || exit $?

#
# Globals
#

export TOOLBOX64_DEBUG
export CNT64_LINT_USER

#
# Main
#

[[ -n "$TOOLBOX64_DEBUG" ]] && bl64_dbg_lib_enable
bl64_os_match "$BL64_OS_ALP" &&
  bl64_check_privilege_root &&
  bl64_check_export 'CNT64_LINT_USER' ||
  exit $?

bl64_msg_all_enable_verbose
bl64_msg_show_task "create lint user (${CNT64_LINT_USER})" &&
  bl64_iam_user_add "$CNT64_LINT_USER" ||
  exit $?

bl64_fs_cleanup_full
exit 0
