#!/usr/bin/env bash

# shellcheck source=SCRIPTDIR/../loader/bashlib64.bash
source '/bashlib64.bash' || exit $?

#
# Globals
#

export CNT64_LINT_USER
export CNT64_LINT_VOLUME

#
# Main
#

declare cnt64_tools='shellcheck'

bl64_os_match "$BL64_OS_ALP" &&
  bl64_check_privilege_root &&
  bl64_pkg_setup ||
  exit $?

bl64_msg_all_enable_verbose
# shellcheck disable=SC2086
bl64_msg_show_task "create lint user (${CNT64_LINT_USER})" &&
  bl64_iam_user_add "$CNT64_LINT_USER" &&
  bl64_msg_show_task "create source mount point (${CNT64_LINT_VOLUME})" &&
  bl64_fs_mkdir_full "$CNT64_LINT_VOLUME" &&
  bl64_msg_show_task "install application (${cnt64_tools})" &&
  bl64_pkg_deploy $cnt64_tools ||
  exit $?

bl64_fs_cleanup_full
exit 0
