---
name: "Deliver / Container / Shell Lint"

concurrency:
  group: "deliver-docker-shell-lint"
  cancel-in-progress: true

env:
  DEV_CICD_DEBUG: ""

on:
  workflow_dispatch:
  workflow_call:

jobs:
  deliver-docker-shell-lint:
    runs-on: "ubuntu-latest"
    permissions: "write-all"

    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      DEV_AUTH_CONTAINER_USER: "${{ secrets.DEV_AUTH_CONTAINER_USER }}"
      DEV_AUTH_COSIGN_USER: "${{ secrets.DEV_AUTH_COSIGN_USER }}"

    strategy:
      matrix:
        scope:
          - "SHELL_LINT_L0"

    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare base tools"
        run: "./bin/dev-lib-installer64"

      - name: "Prepare docker tool"
        run: "./bin/dev-auth-container"

      - name: "Prepare cosign tool"
        run: "./bin/dev-lib-cosign && ./bin/dev-auth-cosign"

      - name: "Build and publish container images"
        run: "./bin/dev-build-cntbuild ${{ matrix.scope }} ON"
...
