---
name: "Deliver/Container/Mirror"

concurrency:
  group: "deliver-docker-mirror"
  cancel-in-progress: true

env:
  DEV_CICD_DEBUG: ${{ vars.DEV_CICD_DEBUG || 'NONE' }}
  DEV_CICD_DEBUG_BASH: ${{ vars.DEV_CICD_DEBUG_BASH || '' }}
  BL64_LIB_CICD: ${{ vars.BL64_LIB_CICD || 'YES' }}

on:
  workflow_dispatch:
    inputs:
      target:
        required: true
        type: choice
        description: Name of the mirror container
        options:
          - "ARCHLINUX"
          - "KALILINUX"

jobs:
  deliver-docker-mirror:
    runs-on: "ubuntu-latest"
    permissions: "write-all"

    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      DEV_AUTH_CONTAINER_USER: "${{ secrets.DEV_AUTH_CONTAINER_USER }}"
      DEV_AUTH_COSIGN_USER: "${{ secrets.DEV_AUTH_COSIGN_USER }}"

    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Cache base tools"
        uses: "actions/cache@v5"
        with:
          path: |
            ./lib/bl64
            ./lib/inst64
          key: "dev-tools"

      - name: "Cache module tools"
        uses: "actions/cache@v5"
        with:
          path: |
            ./lib/cosign
          key: "dev-cosign"

      - name: "Download tools"
        run: |
          ./bin/dev-lib-base &&
          ./bin/dev-lib-cosign

      - name: "Prepare for delivery"
        run: |
          ./bin/dev-auth-container &&
          ./bin/dev-auth-cosign

      - name: "Deliver distributable content"
        run: "./bin/dev-build-project MIRROR_${{ github.event.inputs.target }} ON"
...
