---
name: "Deliver / Container / Toolbox"

env:
  DEV_CICD_DEBUG: ""

on:
  workflow_dispatch:

jobs:
  deliver-docker-toolbox-l0:
    runs-on: "ubuntu-latest"
    permissions: "write-all"

    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      DEV_AUTH_CONTAINER_USER: "${{ secrets.DEV_AUTH_CONTAINER_USER }}"
      DEV_AUTH_COSIGN_USER: "${{ secrets.DEV_AUTH_COSIGN_USER }}"

    strategy:
      matrix:
        scope:
          - "TOOLBOX_L0"

    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare base tools"
        run: "./bin/dev-lib-installer64"

      - name: "Prepare docker tool"
        run: "./bin/dev-auth-container"

      - name: "Prepare cosign tool"
        run: "./bin/dev-lib-cosign && ./bin/dev-auth-cosign"

      - name: "Build and publish container images"
        run: "./bin/dev-build-cntbuild ${{ matrix.scope }} ON"

  deliver-docker-toolbox-l1:
    runs-on: "ubuntu-latest"
    permissions: "write-all"

    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      DEV_AUTH_CONTAINER_USER: "${{ secrets.DEV_AUTH_CONTAINER_USER }}"
      DEV_AUTH_COSIGN_USER: "${{ secrets.DEV_AUTH_COSIGN_USER }}"

    strategy:
      matrix:
        scope:
          - "TOOLBOX_L1"

    needs:
        - "deliver-docker-toolbox-l0"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare base tools"
        run: "./bin/dev-lib-installer64"

      - name: "Prepare docker tool"
        run: "./bin/dev-auth-container"

      - name: "Prepare cosign tool"
        run: "./bin/dev-lib-cosign && ./bin/dev-auth-cosign"

      - name: "Build and publish container images"
        run: "./bin/dev-build-cntbuild ${{ matrix.scope }} ON"

  deliver-docker-toolbox-l2:
    runs-on: "ubuntu-latest"
    permissions: "write-all"

    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      DEV_AUTH_CONTAINER_USER: "${{ secrets.DEV_AUTH_CONTAINER_USER }}"
      DEV_AUTH_COSIGN_USER: "${{ secrets.DEV_AUTH_COSIGN_USER }}"

    strategy:
      matrix:
        scope:
          - "TOOLBOX_L2"

    needs:
        - "deliver-docker-toolbox-l1"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare base tools"
        run: "./bin/dev-lib-installer64"

      - name: "Prepare docker tool"
        run: "./bin/dev-auth-container"

      - name: "Prepare cosign tool"
        run: "./bin/dev-lib-cosign && ./bin/dev-auth-cosign"

      - name: "Build and publish container images"
        run: "./bin/dev-build-cntbuild ${{ matrix.scope }} ON"

  deliver-docker-toolbox-l3:
    runs-on: "ubuntu-latest"
    permissions: "write-all"

    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      DEV_AUTH_CONTAINER_USER: "${{ secrets.DEV_AUTH_CONTAINER_USER }}"
      DEV_AUTH_COSIGN_USER: "${{ secrets.DEV_AUTH_COSIGN_USER }}"

    strategy:
      matrix:
        scope:
          - "TOOLBOX_L3"

    needs:
        - "deliver-docker-toolbox-l2"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare base tools"
        run: "./bin/dev-lib-installer64"

      - name: "Prepare docker tool"
        run: "./bin/dev-auth-container"

      - name: "Prepare cosign tool"
        run: "./bin/dev-lib-cosign && ./bin/dev-auth-cosign"

      - name: "Build and publish container images"
        run: "./bin/dev-build-cntbuild ${{ matrix.scope }} ON"
...
