---
name: "Deliver / Container / K8S Lint"

env:
  DEV_CICD_DEBUG: ""

on:
  workflow_dispatch:

jobs:
  deliver-docker-k8s-lint:
    runs-on: "ubuntu-latest"

    permissions:
      contents: "read"
      packages: "write"

    env:
      CNTBUILD_LOGIN_PASSWORD: "${{ secrets.GITHUB_TOKEN }}"

    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib-installer64 && ./bin/dev-lib-bashlib64"

      - name: "Build and publish container images"
        shell: 'script -q -e -c "bash {0}"'
        run: "./bin/dev-build-container k8s_lint ON"
...
