---
name: "Deliver / Container"

on:
  workflow_dispatch:

jobs:
  deliver-docker-all:
    runs-on: "ubuntu-latest"

    permissions:
      contents: read
      packages: write

    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib"

      - name: "Run Bash linter"
        shell: 'script -q -e -c "bash {0}"'
        run: "./bin/dev-container all 0"
...
