---
name: "Deliver / Container / Bash Test / Remaining Levels"

on:
  workflow_dispatch:

jobs:
  deliver-docker-bash-test-b:
    runs-on: "ubuntu-latest"

    permissions:
      contents: "read"
      packages: "write"

    env:
      CNTBUILD_LOGIN_PASSWORD: "${{ secrets.GITHUB_TOKEN }}"

    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib-bashlib64"

      - name: "Build and publish container images"
        shell: 'script -q -e -c "bash {0}"'
        run: "./bin/dev-build-container bash_test_b ON"
...
