---
name: "Deliver/Container/Container Lint"

concurrency:
  group: "deliver-docker-container-lint"
  cancel-in-progress: true

env:
  DEV_CICD_DEBUG: ${{ vars.DEV_CICD_DEBUG || 'NONE' }}
  DEV_CICD_DEBUG_BASH: ${{ vars.DEV_CICD_DEBUG_BASH || '' }}
  BL64_LIB_CICD: ${{ vars.BL64_LIB_CICD || 'YES' }}

on:
  workflow_dispatch:
  workflow_call:

jobs:
  deliver-docker-container-lint:
    runs-on: "ubuntu-latest"
    permissions: "write-all"

    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      DEV_AUTH_CONTAINER_USER: "${{ secrets.DEV_AUTH_CONTAINER_USER }}"
      DEV_AUTH_COSIGN_USER: "${{ secrets.DEV_AUTH_COSIGN_USER }}"

    strategy:
      matrix:
        scope:
          - "CONTAINER_LINT_L0"

    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Cache base tools"
        uses: "actions/cache@v5"
        with:
          path: |
            ./lib/bl64
            ./lib/inst64
          key: "dev-tools"

      - name: "Cache module tools"
        uses: "actions/cache@v5"
        with:
          path: |
            ./lib/cosign
          key: "dev-cosign"

      - name: "Download tools"
        run: |
          ./bin/dev-lib-base &&
          ./bin/dev-lib-cosign

      - name: "Prepare for delivery"
        run: |
          ./bin/dev-auth-container &&
          ./bin/dev-auth-cosign

      - name: "Deliver distributable content"
        run: "./bin/dev-build-project ${{ matrix.scope }} ON"
...
