---
# Template Version: 2.1.0
name: "Lint / Bash / TestManSH"

on:
  push:
    paths:
      - "src/**"

jobs:
  lint-bash-testmansh:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib"

      - name: "Run Bash linter"
        shell: 'script -q -e -c "bash {0}"'
        run: "./bin/dev-lint"
...
