---
# Template: 4.1.0
name: "Lint / Bash"

env:
  DEV_CICD_DEBUG: ""

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "feature/**"
    paths:
      - "src/cntbuild/*"
      - "src/helper-*/*"
      - "src/installer/**"

jobs:
  lint-bash:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib-installer64 && ./bin/dev-lib-bashlib64 && ./bin/dev-lib-testmansh"

      - name: "Build app"
        shell: 'script -q -e -c "bash {0}"'
        run: "./bin/dev-build-cli"

      - name: "Lint app"
        shell: 'script -q -e -c "bash {0}"'
        run: "./bin/dev-lint-bash"
...
