---
# template: 1.9.0
name: "Lint/Hadolint"

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

env:
  DEV_CICD_DEBUG: ${{ vars.DEV_CICD_DEBUG || 'NONE' }}
  DEV_CICD_DEBUG_BASH: ${{ vars.DEV_CICD_DEBUG_BASH || '' }}
  BL64_LIB_CICD: ${{ vars.BL64_LIB_CICD || 'YES' }}

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "feature/**"
      - "release/**"
    paths:
      - "src/dockerfiles/*/*"

jobs:
  lint-hadolint:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Cache base tools"
        uses: "actions/cache@v5"
        with:
          path: |
            ./lib/bl64
            ./lib/inst64
          key: "dev-tools"

      - name: "Cache module tools"
        uses: "actions/cache@v5"
        with:
          path: |
            ./lib/hadolint
          key: "dev-hadolint"

      - name: "Download tools"
        run: |
          ./bin/dev-lib-base &&
          ./bin/dev-lib-hadolint

      - name: "Run tests"
        run: "./bin/dev-lint-hadolint"
...
