---
name: "Pack/Container/Pen Test"

concurrency:
  group: "pack-docker-pen-test"
  cancel-in-progress: true

env:
  DEV_CICD_DEBUG: ${{ vars.DEV_CICD_DEBUG || 'NONE' }}
  DEV_CICD_DEBUG_BASH: ${{ vars.DEV_CICD_DEBUG_BASH || '' }}

on:
  workflow_dispatch:
  workflow_call:

jobs:
  pack-docker-pen-test:
    runs-on: "ubuntu-latest"
    permissions: "write-all"

    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      DEV_AUTH_DOCKER_USER: "${{ secrets.DEV_AUTH_DOCKER_USER }}"
      DEV_AUTH_COSIGN_USER: "${{ secrets.DEV_AUTH_COSIGN_USER }}"

    strategy:
      matrix:
        scope:
          - "PEN_TEST_L0"

    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Cache base tools"
        uses: "actions/cache@v5"
        with:
          path: |
            ./lib/bl64
            ./lib/inst64
          key: "dev-tools"

      - name: "Cache module tools"
        uses: "actions/cache@v5"
        with:
          path: |
            ./lib/cosign
          key: "dev-cosign"

      - name: "Download tools"
        run: |
          ./bin/dev-lib-base &&
          ./bin/dev-lib-cosign

      - name: "Prepare for delivery"
        run: |
          ./bin/dev-auth-docker &&
          ./bin/dev-auth-cosign

      - name: "Deliver distributable content"
        run: "./bin/dev-pack-project ${{ matrix.scope }} ON"
...
